# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'tedx_larochelle_app' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for tedx_larochelle_app
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'
  pod 'GoogleSignIn'


  target 'tedx_larochelle_app-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RNGoogleSignin', :path => '../node_modules/react-native-google-signin'
    pod 'React', :path => '../node_modules/react-native'
    pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
    
    pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

    pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  end

  target 'tedx_larochelle_appTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
